inherit_from:
  - .rubocop_airbnb.yml
Rails:
  Enabled: true
AsciiComments:
  Enabled: false
AllCops:
  Exclude:
    - 'db/**/*'
    - 'bin/*'
    - 'config/environments/*'
    - 'config/application.rb'
    - 'config/initializers/*'
    - 'config/spring.rb'
    - 'lib/tasks/*'
    - 'vendor/**/*'
    - 'path/ruby'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'